// Generated by ReScript, PLEASE EDIT WITH CARE


async function handler($$event, _context) {
  console.log($$event.queryStringParameters);
  var a = $$event.queryStringParameters.a;
  var message = a !== undefined ? "Hello " + a : "No parameter for a was found";
  return {
          statusCode: 200,
          body: JSON.stringify({
                message: message
              })
        };
}

export {
  handler ,
}
/* No side effect */
