// Generated by ReScript, PLEASE EDIT WITH CARE


async function handler(_event, _context) {
  return {
          statusCode: 200,
          body: JSON.stringify({
                message: "Hello World"
              })
        };
}

export {
  handler ,
}
/* No side effect */
