// Generated by ReScript, PLEASE EDIT WITH CARE


async function handler($$event, _context) {
  console.log($$event);
  return {
          statusCode: 200,
          body: JSON.stringify({
                message: "Hello World"
              })
        };
}

export {
  handler ,
}
/* No side effect */
