// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Data = require("../src/data.js");
var Zora = require("zora");
var MockPerson = require("./mockPerson.js");
var S$ReScriptStruct = require("rescript-struct/src/S.js");

var expected = {
  id: 1,
  name: "John Doe"
};

Zora.test("should parse good data", (function (t) {
        var result = S$ReScriptStruct.parseWith(MockPerson.mock, Data.personStruct);
        t.equal(result, {
              TAG: /* Ok */0,
              _0: expected
            }, "should be ok");
      }));

exports.expected = expected;
/*  Not a pure module */
