// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as Faunadb from "../../faunadb.js";

async function handler(param) {
  var q = Curry._2(Faunadb.query.Create, Curry._1(Faunadb.query.Ref, "classes/todo"), {
        data: {
          title: "working!"
        }
      });
  console.log(q);
  var res = await Faunadb.client.query(q);
  return {
          statusCode: 200,
          body: JSON.stringify(res)
        };
}

export {
  handler ,
}
/* Faunadb Not a pure module */
