// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as Faunadb from "../../faunadb.js";
import * as Core__JSON from "@rescript/core/src/Core__JSON.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";

async function handler($$event) {
  var createQuery = function (t) {
    return Curry._2(Faunadb.query.Create, Curry._1(Faunadb.query.Ref, "classes/todo"), {
                data: t
              });
  };
  var body = Core__JSON.Decode.object($$event.body);
  if (body === undefined) {
    return {
            statusCode: 400,
            body: JSON.stringify({
                  error: "body isn't valid JSON."
                })
          };
  }
  var query = createQuery(Caml_option.valFromOption(body));
  var res = await Faunadb.client.query(query);
  return {
          statusCode: 200,
          body: JSON.stringify(res)
        };
}

export {
  handler ,
}
/* Faunadb Not a pure module */
