// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core__Option from "@rescript/core/src/Core__Option.js";

async function handler($$event, _context) {
  var message = Core__Option.map($$event.queryStringParameters.name, (function (prim) {
          return prim.toUpperCase();
        }));
  if (message !== undefined) {
    return {
            statusCode: 200,
            body: JSON.stringify({
                  message: "Hello " + message
                })
          };
  } else {
    return {
            statusCode: 200,
            body: JSON.stringify({
                  message: "No name was provided :("
                })
          };
  }
}

export {
  handler ,
}
/* No side effect */
