// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as Faunadb from "../../faunadb.mjs";
import * as S$ReScriptStruct from "rescript-struct/src/S.mjs";

var personStruct = S$ReScriptStruct.object(function (o) {
      return {
              id: S$ReScriptStruct.field(o, "Id", S$ReScriptStruct.$$int(undefined)),
              firstName: S$ReScriptStruct.field(o, "FirstName", S$ReScriptStruct.string(undefined)),
              lastName: S$ReScriptStruct.field(o, "LastName", S$ReScriptStruct.string(undefined))
            };
    });

async function handler($$event) {
  var createQuery = function (t) {
    return Curry._2(Faunadb.query.Create, Curry._1(Faunadb.query.Ref, "classes/person"), {
                data: t
              });
  };
  var b = JSON.parse($$event.body);
  var query = createQuery(b);
  var res = await Faunadb.client.query(query);
  return {
          statusCode: 200,
          body: JSON.stringify(res)
        };
}

export {
  personStruct ,
  handler ,
}
/* personStruct Not a pure module */
