// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var Faunadb = require("../../faunadb.js");
var S$ReScriptStruct = require("rescript-struct/src/S.js");

var personStruct = S$ReScriptStruct.object(function (o) {
      return {
              id: S$ReScriptStruct.field(o, "Id", S$ReScriptStruct.$$int(undefined)),
              firstName: S$ReScriptStruct.field(o, "FirstName", S$ReScriptStruct.string(undefined)),
              lastName: S$ReScriptStruct.field(o, "LastName", S$ReScriptStruct.string(undefined))
            };
    });

async function handler($$event) {
  var createQuery = function (t) {
    return Curry._2(Faunadb.query.Create, Curry._1(Faunadb.query.Ref, "classes/person"), {
                data: t
              });
  };
  var b = S$ReScriptStruct.parseWith($$event.body, personStruct);
  if (b.TAG !== /* Ok */0) {
    return {
            statusCode: 400,
            body: S$ReScriptStruct.$$Error.toString(b._0)
          };
  }
  var query = createQuery(b._0);
  var res = await Faunadb.client.query(query);
  return {
          statusCode: 200,
          body: JSON.stringify(res)
        };
}

exports.personStruct = personStruct;
exports.handler = handler;
/* personStruct Not a pure module */
