// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Data = require("../../data.js");
var Curry = require("rescript/lib/js/curry.js");
var Faunadb = require("../../faunadb.js");
var S$ReScriptStruct = require("rescript-struct/src/S.js");

async function handler($$event) {
  var createQuery = function (t) {
    return Curry._2(Faunadb.query.Create, Curry._1(Faunadb.query.Ref, "classes/person"), {
                data: t
              });
  };
  var b = S$ReScriptStruct.parseWith($$event.body, Data.personStruct);
  if (b.TAG !== /* Ok */0) {
    return {
            statusCode: 400,
            body: S$ReScriptStruct.$$Error.toString(b._0)
          };
  }
  var query = createQuery(b._0);
  var res = await Faunadb.client.query(query);
  return {
          statusCode: 200,
          body: JSON.stringify(res)
        };
}

exports.handler = handler;
/* Data Not a pure module */
