// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as Faunadb from "../../faunadb.mjs";

async function handler($$event) {
  var createQuery = function (t) {
    return Curry._2(Faunadb.query.Create, Curry._1(Faunadb.query.Ref, "classes/todo"), {
                data: t
              });
  };
  var b = JSON.parse($$event.body);
  var query = createQuery(b);
  var res = await Faunadb.client.query(query);
  return {
          statusCode: 200,
          body: JSON.stringify(res)
        };
}

export {
  handler ,
}
/* Faunadb Not a pure module */
