// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Client = require("react-dom/client");
var JsxRuntime = require("react/jsx-runtime");

var rootElement = document.querySelector("#root");

if (!(rootElement == null)) {
  var root = Client.createRoot(rootElement);
  root.render(JsxRuntime.jsx("div", {
            children: "Hello world!"
          }));
}

/* rootElement Not a pure module */
