// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Calendar = require("./calendar.js");
var Material = require("@mui/material");
var Client = require("react-dom/client");
var JsxRuntime = require("react/jsx-runtime");

var rootElement = document.querySelector("#root");

if (!(rootElement == null)) {
  var root = Client.createRoot(rootElement);
  root.render(JsxRuntime.jsx(Material.Paper, {
            children: JsxRuntime.jsx(Calendar.make, {})
          }));
}

/* rootElement Not a pure module */
