// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var JsxRuntime = require("react/jsx-runtime");
var DxReactGrid = require("@devexpress/dx-react-grid");
var DxReactScheduler = require("@devexpress/dx-react-scheduler");
var DxReactSchedulerMaterialUi = require("@devexpress/dx-react-scheduler-material-ui");

var currentDate = "2018-11-01";

function Calendar(props) {
  return JsxRuntime.jsxs(DxReactSchedulerMaterialUi.Scheduler, {
              data: [{
                  startDate: "2018-11-01T09:45",
                  endDate: "2018-11-01T11:00",
                  title: "Meeting",
                  members: [
                    1,
                    2
                  ],
                  id: 1
                }],
              children: [
                JsxRuntime.jsx(DxReactScheduler.ViewState, {
                      currentDate: currentDate
                    }),
                JsxRuntime.jsx(DxReactSchedulerMaterialUi.DayView, {
                      startDayHour: 9,
                      endDayHour: 14
                    }),
                JsxRuntime.jsx(DxReactScheduler.GroupingState, {
                      grouping: [{
                          resourceName: "members"
                        }]
                    }),
                JsxRuntime.jsx(DxReactSchedulerMaterialUi.Appointments, {}),
                JsxRuntime.jsx(DxReactSchedulerMaterialUi.Resources, {
                      mainSourceName: "members",
                      data: [{
                          id: 1,
                          fieldName: "members",
                          instances: [{
                              id: 1,
                              text: "foobar"
                            }]
                        }]
                    }),
                JsxRuntime.jsx(DxReactGrid.IntegratedGrouping, {})
              ]
            });
}

var make = Calendar;

exports.currentDate = currentDate;
exports.make = make;
/* react/jsx-runtime Not a pure module */
