// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var JsxRuntime = require("react/jsx-runtime");
var DxReactScheduler = require("@devexpress/dx-react-scheduler");
var DxReactSchedulerMaterialUi = require("@devexpress/dx-react-scheduler-material-ui");

var currentDate = "2018-11-01";

function Calendar(props) {
  return JsxRuntime.jsxs(DxReactSchedulerMaterialUi.Scheduler, {
              data: [{
                  startDate: "2018-11-01T09:45",
                  endDate: "2018-11-01T11:00",
                  title: "Meeting"
                }],
              children: [
                JsxRuntime.jsx(DxReactScheduler.ViewState, {
                      currentDate: currentDate
                    }),
                JsxRuntime.jsx(DxReactSchedulerMaterialUi.DayView, {
                      startDayHour: 9,
                      endDayHour: 14
                    }),
                JsxRuntime.jsx(DxReactSchedulerMaterialUi.Appointments, {})
              ]
            });
}

var make = Calendar;

exports.currentDate = currentDate;
exports.make = make;
/* react/jsx-runtime Not a pure module */
