// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Faunadb from "faunadb";

var client = new Faunadb.Client({
      secret: "fnAE_XRDsoAAVm3S7kTRu18tPSPK9FcZxb1zPve6"
    });

var query = Faunadb.query;

export {
  client ,
  query ,
}
/* client Not a pure module */
