// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Faunadb from "faunadb";

var client = new Faunadb.Client({
      secret: process.env.FAUNADB_SERVER_SECRET
    });

var query = Faunadb.query;

export {
  client ,
  query ,
}
/* client Not a pure module */
