// Generated by ReScript, PLEASE EDIT WITH CARE

import * as S$ReScriptStruct from "rescript-struct/src/S.mjs";

var personStruct = S$ReScriptStruct.object(function (o) {
      return {
              id: S$ReScriptStruct.field(o, "Id", S$ReScriptStruct.$$int(undefined)),
              firstName: S$ReScriptStruct.field(o, "FirstName", S$ReScriptStruct.string(undefined)),
              lastName: S$ReScriptStruct.field(o, "LastName", S$ReScriptStruct.string(undefined))
            };
    });

export {
  personStruct ,
}
/* personStruct Not a pure module */
